### ISSUE TITLE
Bolt\Extension\Bolt\ClientLogin\Exception\ProviderException

### ISSUE THREAD

**Issue by andyjessop** [bolt/ClientLogin#12] opened 2015-06-03 10:04 UTC
I've installed this plugin on top of Bolt v2.2.0, and I visit /authenticate/login. I get the following error:

    Bolt\Extension\Bolt\ClientLogin\Exception\ProviderException

And in the system log:

    /var/www/html/bolt/extensions/vendor/bolt/clientlogin/src/Session.php
    line: 453

In the config file, I have checked that:

    providers:
        Password:
            enabled: true

**Comment by GawainLynch** [comment] 2015-06-03 10:18
A couple of things:

#### Version
Make sure you're using `dev-master` version of ClientLogin for the time being. I had to move away from HybridAuth as the library is just fundamentally broken and I was planning on testing/tagging a release this week

#### Error
That error you're getting is due to that route needing a HTTP GET query parameter, and the route itself isn't intended as a "user route" as such… 
```php
        if (empty($provider)) {
            throw new ProviderException('Invalid provider.');
        }
```
Though if you want to provide your own link, there is no reason it won't work. Easiest way get a idea of how it's working at the moment is using the login buttons with the built-in Twig function.

#### Password Login
This is still very much a work in progress. It works, but I am not sure if I have hooked up the registration stuff yet.

**Comment by andyjessop** [comment] 2015-06-03 10:24
Thanks for that. I have indeed installed from dev-master as I wanted the latest version. So, after visiting /auth/login?provider=Password, I get the following error: `The controller must return a response (null given).`

I did a var_dump($response) on line 85 of ClientLoginController to check the response - [here's the screenshot of the result](http://i.imgur.com/wRA6jhE.png).

**Comment by GawainLynch** [comment] 2015-06-03 10:34
Ah… that. The way that `$response` is being done was to work around a regression bug in Bolt 2.2 that is no longer there, so for the second, change:

```php
        $response->prepare($request);
        $response->send();
```
To
```php
        return $response;
```
I'll get on to this stuff for a stable release this week! :grin:

**Comment by andyjessop** [comment] 2015-06-03 10:35
Great - thanks. That works now.

**Comment by GawainLynch** [comment] 2016-02-04 12:57
Closing this as I am discontinuing the extension. It has been merged with [`bolt/members`](https://github.com/bolt/Members) and is for Bolt v3.0+

**Closed by GawainLynch** 2016-02-04 12:57 UTC
